# Generated by Django 4.1.3 on 2022-12-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SchoolId', models.CharField(max_length=4)),
                ('SchoolName', models.CharField(max_length=300)),
                ('SchoolAddress', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'PySchools',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
